# Generated by Django 2.2.6 on 2019-12-27 01:07

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField(help_text='Write something about you')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='code_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'draft')], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggtrends.BlogAuthor')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggtrends.Category')),
            ],
            options={
                'verbose_name_plural': 'code_post',
                'ordering': ['-created_at', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('Parent_Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggtrends.Category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('videofile', models.FileField(blank=True, upload_to='')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('links', models.URLField(blank=True)),
                ('madewith', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('compatible', models.CharField(blank=True, max_length=100)),
                ('responsive', models.CharField(blank=True, max_length=100)),
                ('dependencies', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggtrends.code_post')),
            ],
            options={
                'verbose_name_plural': 'Code Post Examples',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='code_post',
            name='sub_catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggtrends.Sub_Category'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'draft')], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggtrends.BlogAuthor')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggtrends.Category')),
                ('sub_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggtrends.Sub_Category')),
            ],
            options={
                'ordering': ['-created_at', '-updated'],
            },
        ),
    ]
