# Generated by Django 2.2.6 on 2019-12-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggtrends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-Date', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='code_post',
            options={'ordering': ['-Date', '-updated'], 'verbose_name_plural': 'code_post'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='code_post',
            old_name='created_at',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='created_at',
            new_name='Date',
        ),
    ]
