# Generated by Django 2.2.6 on 2019-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggtrends', '0002_auto_20191227_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_post',
            name='code_post',
            field=models.BooleanField(default=False),
        ),
    ]
