# Generated by Django 2.2.6 on 2019-12-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggtrends', '0003_code_post_code_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_post',
            name='code_post',
            field=models.BooleanField(default=True),
        ),
    ]
