# Generated by Django 2.2.6 on 2019-12-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggtrends', '0004_auto_20191230_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Parent Categories',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='Parent_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aggtrends.Parent_Category'),
        ),
    ]
