# Generated by Django 2.2.6 on 2019-12-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggtrends', '0005_auto_20191231_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_post',
            name='Parent_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aggtrends.Parent_Category'),
        ),
    ]
